clouds:
  mockcloud:
    plugin: cloudmarker.clouds.mockcloud.MockCloud

stores:
  filestore:
    plugin: cloudmarker.stores.filestore.FileStore
  mongodbstore:
    plugin: cloudmarker.stores.mongodbstore.MongoDBStore

events:
  mockevent:
    plugin: cloudmarker.events.mockevent.MockEvent
  firewallevent:
    plugin: cloudmarker.evengts.firewallevent.FirewallEvent

alerts:
  filestore:
    plugin: cloudmarker.stores.filestore.FileStore

audits:
  mockaudit:
    clouds:
      - mockcloud
    stores:
      - filestore
    events:
      - mockevent
    alerts:
      - filestore

run:
  - mockaudit


logger:

  version: 1
  disable_existing_loggers: false

  formatters:
    simple:
      format: "%(asctime)s %(levelname)s %(name)s:%(lineno)d - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: logs/cloudmarker.log
      when: midnight
      encoding: utf8

  loggers:
    adal-python:
      level: WARNING

  root:
    level: INFO
    handlers:
      - console
      - file_handler


schedule: "00:00"
