clouds:
  mockcloud:
    plugin: cloudmarker.clouds.mockcloud.MockCloud

stores:
  filestore:
    plugin: cloudmarker.stores.filestore.FileStore

checks:
  mockcheck:
    plugin: cloudmarker.checks.mockcheck.MockCheck

alerts:
  filestore:
    plugin: cloudmarker.stores.filestore.FileStore

audits:
  mockaudit:
    clouds:
      - mockcloud
    stores:
      - filestore
    checks:
      - mockcheck
    alerts:
      - filestore

run:
  - mockaudit
